_prefs: 
  mapid: grafa.e8deadfc
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 7.4209
  - 46.9514
  - 16
description: Orienteering style based on ISOM 2000 spec and Chlosterwald data set (OCAD).
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 16
name: Orienteering Style
source: "mapbox:///grafa.7e365fab"
styles: 
  - style.mss
template: ''
